### ISSUE TITLE
Build a Chatbot with Build Apps & AI Core

### ISSUE THREAD

**Issue by jung-thomas** [SAP-samples/teched2024-developer-keynote#2]
Is there any source code, screenshots or instructions from your demo that you want to share?  If so please add into a folder in this project and a link from the main readme

**Comment by neelamegams** [comment]
Added the readme and screenshots for the SAP Build Demo session(Dev keynote deconstructed) https://github.com/SAP-samples/teched2024-developer-keynote/tree/main?tab=readme-ov-file#build-a-chatbot-with-build-apps-ai-core

**Comment by neelamegams** [comment]
Done. Closing this issue.
